from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from services.gemini import generate_text
from services.prompts import get_explain_prompt

router = APIRouter(prefix="/explain", tags=["Explain"])

class ExplainRequest(BaseModel):
    topic: str = Field(..., example="Binary Search", description="The topic to explain")

class ExplainResponse(BaseModel):
    answer: str = Field(..., description="Simple explanation of the topic generated by Gemini")

from utils.response import UnifiedResponse

@router.post("", response_model=UnifiedResponse[ExplainResponse])
def explain_topic(request: ExplainRequest):
    try:
        prompt = get_explain_prompt(request.topic)
        explanation = generate_text(prompt)
        data = ExplainResponse(answer=explanation.strip())
        return UnifiedResponse(success=True, data=data)
    except Exception as e:
        return UnifiedResponse(success=False, error=str(e))
