from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field, field_validator
from services.gemini import generate_text
from services.prompts import get_explain_prompt
from utils.response import UnifiedResponse

router = APIRouter(prefix="/explain", tags=["Explain"])

class ExplainRequest(BaseModel):
    topic: str = Field(..., example="Binary Search", description="The topic to explain")

    @field_validator("topic")
    @classmethod
    def topic_must_not_be_empty(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("Topic cannot be empty or whitespace")
        return v.strip()

class ExplainResponse(BaseModel):
    answer: str = Field(..., description="Simple explanation of the topic generated by Gemini")

from utils.logger import get_logger

logger = get_logger("ExplainRoute")

@router.post("", response_model=UnifiedResponse[ExplainResponse])
def explain_topic(request: ExplainRequest):
    logger.info(f"Incoming POST /explain request for topic: '{request.topic}'")
    try:
        prompt = get_explain_prompt(request.topic)
        explanation = generate_text(prompt)
        data = ExplainResponse(answer=explanation.strip())
        logger.info("Successfully generated explanation.")
        return UnifiedResponse(success=True, data=data)
    except Exception as e:
        logger.warning(f"Error in explain_topic, falling back. Error: {str(e)}")
        fallback_msg = (
            f"We are temporarily unable to reach the AI tutor. "
            f"However, '{request.topic}' is a key concept that you can study in standard textbooks, "
            f"reviewing its definition, core properties, and practical examples. "
            f"Please try again shortly. (Error: {str(e)})"
        )
        data = ExplainResponse(answer=fallback_msg)
        return UnifiedResponse(success=True, data=data)
