import os
import uuid
from fastapi import APIRouter, HTTPException, UploadFile, File, Form
from pydantic import BaseModel, Field
from typing import List, Dict, Any
from utils.response import UnifiedResponse
from utils.logger import get_logger
from services.rag import (
    UPLOADS_DIR,
    extract_text_from_pdf,
    split_text_into_chunks,
    get_embeddings,
    build_faiss_index,
    retrieve_relevant_chunks
)
from services.gemini import generate_text

logger = get_logger("RAGRoute")
router = APIRouter(prefix="/rag", tags=["RAG (FAISS)"])

class UploadResponse(BaseModel):
    doc_id: str = Field(..., description="Unique document ID used for querying the document later")
    filename: str = Field(..., description="Uploaded filename")
    chunks_count: int = Field(..., description="Number of text chunks generated and indexed")

class QueryRequest(BaseModel):
    doc_id: str = Field(..., description="The document ID to query")
    query: str = Field(..., description="The student's question/query")

class QueryResponse(BaseModel):
    answer: str = Field(..., description="Contextual answer generated by AI using retrieved document chunks")
    retrieved_chunks: List[str] = Field(..., description="The source chunks retrieved from the FAISS database")

@router.post("/upload", response_model=UnifiedResponse[UploadResponse])
async def upload_document(
    file: UploadFile = File(...),
    chunk_size: int = Form(1000),
    chunk_overlap: int = Form(200)
):
    logger.info(f"Incoming POST /rag/upload for file: '{file.filename}'")
    try:
        # Generate unique doc_id
        doc_id = str(uuid.uuid4())
        
        # Save uploaded file
        file_ext = os.path.splitext(file.filename)[1].lower()
        file_path = os.path.join(UPLOADS_DIR, f"{doc_id}{file_ext}")
        
        with open(file_path, "wb") as buffer:
            content = await file.read()
            buffer.write(content)
            
        logger.info(f"File saved to {file_path}")
        
        # Extract text
        if file_ext == ".pdf":
            text = extract_text_from_pdf(file_path)
        else:
            # Assume text/markdown/py/js file
            try:
                text = content.decode("utf-8")
            except UnicodeDecodeError:
                text = content.decode("latin-1")
                
        if not text.strip():
            raise HTTPException(status_code=400, detail="The uploaded file contains no readable text.")
            
        # Split text into chunks
        chunks = split_text_into_chunks(text, chunk_size, chunk_overlap)
        if not chunks:
            raise HTTPException(status_code=400, detail="The file text could not be chunked.")
            
        # Embed chunks
        embeddings = get_embeddings(chunks)
        
        # Build and save FAISS index
        build_faiss_index(doc_id, chunks, embeddings)
        
        data = UploadResponse(
            doc_id=doc_id,
            filename=file.filename,
            chunks_count=len(chunks)
        )
        logger.info(f"Successfully processed and indexed document {doc_id}")
        return UnifiedResponse(success=True, data=data)
        
    except Exception as e:
        logger.error(f"Error processing file upload: {str(e)}")
        return UnifiedResponse(success=False, error=str(e))

@router.post("/query", response_model=UnifiedResponse[QueryResponse])
def query_document(request: QueryRequest):
    logger.info(f"Incoming POST /rag/query for doc_id: {request.doc_id}")
    try:
        # 1. Retrieve relevant chunks from FAISS vector database
        retrieved_chunks = retrieve_relevant_chunks(request.doc_id, request.query, k=3)
        if not retrieved_chunks:
            # Fallback when no context retrieved
            context = "No relevant context found in study material."
        else:
            context = "\n\n---\n\n".join(retrieved_chunks)
            
        # 2. Build prompt containing context and query (strict context-only enforcement)
        prompt = f"""You are a strict study assistant. Answer the student's question based ONLY on the provided context retrieved from their uploaded study material. Do not use outside knowledge or hallucinate facts that are not explicitly stated or directly inferred from the context. If the answer cannot be found in the context, state: "I cannot find the answer to this question in the provided study material."

Context:
{context}

Question:
{request.query}

Answer:"""
        
        # 3. Call LangChain/Gemini for contextual answer
        answer = generate_text(prompt)
        
        data = QueryResponse(
            answer=answer.strip(),
            retrieved_chunks=retrieved_chunks
        )
        logger.info("Successfully answered RAG query.")
        return UnifiedResponse(success=True, data=data)
        
    except Exception as e:
        logger.error(f"Error querying document {request.doc_id}: {str(e)}")
        return UnifiedResponse(success=False, error=str(e))
